version: '3'

tasks:
  run-app:
    deps: [run pocket-base, run-vue-client]

  run-pocket-base:
    dir: ./pocket-base
    cmds:
      - go run main.go serve #default port 8090

  run-vue-client:
    dir: ./vue-client
    cmds:
      - npm run dev

  vue-client-install:
    dir: ./vue-client
    preconditions:
      - test -f package.json
    cmds:
      - npm install