version: '3'

tasks:
  build:
    deps: [assets]
    cmds:
      - go build -v -i main.go

  assets:
    cmds:
      - esbuild --bundle --minify css/index.css > public/bundle.css

  client-install:
    dir: ./client
    preconditions:
      - test -f package.json
    cmds:
      - npm install

  build-all:
    cmds:
      - npm install
      - task client-install