version: '3'

tasks:
  run-app:
    deps: [run-pocket-base, run-vue-client]

  run-pocket-base:
    dir: ./pocket-base
    cmds:
      - go run main.go serve #default port 8090

  run-pocket-base-debug:
    dir: ./pocket-base
    cmds:
      - go run main.go serve --debug #default port 8090

  run-pocket-base-prod:
    dir: ./pocket-base
    cmds:
      - go run main.go serve --http="0.0.0.0:8090"

  run-vue-client:
    dir: ./vue-client
    cmds:
      - npm run dev

  vue-client-install:
    dir: ./vue-client
    preconditions:
      - test -f package.json
    cmds:
      - npm install

  clean-pb:
    dir: ./pocket-base
    cmds:
      - rm -rf ./pb_data

  # Cleans pb_data and runs pocket-base starting from scratch
  run-pocket-base-clean:
    cmds:
      - task: clean-pb
      - task: run-pocket-base